config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  root 'questions#index'

  concern :remarkable do
    resources :remarks, only: [:create, :update, :destroy], shallow: true
  end

  resources :questions, except: [:edit], concerns: :remarkable do
    patch :rating, on: :member
    post :follow, on: :member
    delete :unfollow, on: :member
    resources :answers, only: [:create, :update, :destroy], concerns: :remarkable, shallow: true do
      patch :set_as_best, on: :member
      patch :rating, on: :member
    end
  end

  get 'search' => 'search#index', as: :search

  resources :user_confirmation_requests, only: [:new, :edit, :create, :update] do
    get :confirm, on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Ratingable
  include Taggable

  belongs_to :user
  has_many :answers, dependent: :destroy
  belongs_to :best_answer, class_name: 'Answer'
  has_many :remarks, as: :remarkable, dependent: :destroy
  has_many :attachments, as: :attachmentable, dependent: :destroy
  has_many :ratings, as: :ratingable, dependent: :destroy
  has_and_belongs_to_many :followers, class_name: 'User'
  has_and_belongs_to_many :tags, autosave: true

  validates :user, :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :question, length: { maximum: 2000 }

  scope :ordered_by_creation_date, -> { order(created_at: :desc) }
  scope :last_day, -> { where(created_at: Date.yesterday...Date.today) }

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: proc { |attr| attr['file'].nil? }

  after_create :follow_by_author

  def followed_by?(user)
    followers.exists? user
  end

  def follow_by(user)
    followers << user
  end

  def unfollow_by(user)
    followers.destroy(user)
  end

  def follow_by_author
    follow_by user
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  def index
    @questions = Question.all
    respond_with @questions, each_serializer: QuestionsSerializer
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question
  end

  def create
    respond_with(@question = Question.create(question_params.merge({ user: current_resource_owner })))
  end

  private

  def question_params
    params.require(:question).permit(:title, :question)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include TruncateHtmlHelper

  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  before_action :load_answers, only: [:show, :update]
  before_action :create_answer, only: [:show, :update]
  after_action :publish, only: [:create, :update, :destroy, :rating], if: "@question.errors.empty?"

  respond_to :html, except: :update
  respond_to :js, only: [:show, :update]

  def index
    respond_with(@questions = Question.ordered_by_creation_date)
  end

  def show
    respond_with(@question)
  end

  def new
    respond_with(@question = Question.new)
  end

  def create
    respond_with(@question = Question.create(question_params.merge({ user: current_user })))
  end

  def update
    @question.update(question_params)
    respond_with @question do |format|
      format.js { render :show }
    end
  end

  def destroy
    respond_with(@question.destroy)
  end

  def rating
    @question.rating!(current_user, params[:question][:rating])
    render json: { rating: @question.rating }
  end

  def follow
    @question.follow_by(current_user)
    head :created
  end

  def unfollow
    @question.unfollow_by(current_user)
    head :ok
  end

  private

  def question_params
    params.require(:question).permit(:title, :tags_list, :question, attachments_attributes: [:id, :file, :file_cache, :_destroy])
  end

  def load_answers
    @answers = @question.answers.ordered_by_creation_date
  end

  def create_answer
    @answer = Answer.new
  end

  def publish
    question_hash = @question.as_json(only: [:id, :title])
    question_hash["question"] = truncate_html(@question.question)
    question_hash["no_best_answer"] = @question.best_answer.nil?
    question_hash["created_at"] = @question.created_at.to_s(:long)
    question_hash["updated_at"] = @question.updated_at.to_s(:long)
    question_hash["rating"] = @question.rating
    PrivatePub.publish_to "/questions", action: action_name, question: question_hash

    question_hash["author"] = @question.user.username
    PrivatePub.publish_to "/signed_in/questions", action: action_name, question: question_hash
  rescue
    return
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def tag_color(color_index)
    color_array = %w[label-default label-primary label-success label-info label-warning label-danger]
    color_array[color_index % color_array.count]
  end
end

app/views/questions/_answer.html.slim
.answer-itself style="#{answer.errors.present? ? 'display: none;' : ''}"
  - if answer.user == current_user
    = link_to "Edit Answer", '', class: "btn btn-primary edit-answer-button", data: { answer_id: answer.id }
    | &nbsp;&nbsp;&nbsp;
    button.btn.btn-danger data-toggle="modal" data-target="#deleteAnswerDialog#{answer.id}" Delete Answer
    = render partial: 'questions/delete_dialog', locals: { id: "deleteAnswerDialog#{answer.id}", dialog_text: 'Are you sure?', dialog_yes_path: question_answer_path(@question, answer), remote: true }
  p = answer.answer

.answer-form style="#{answer.errors.present? ? '' : 'display: none;'}"
  = render partial: 'questions/answer_form', locals: { answer: answer, id: answer.id }

app/views/questions/_answers.html.slim
hr
h3 Answers
- @answers.each do |answer|
  div id="answer-#{answer.id}"
    = render partial: 'questions/answer', locals: { answer: answer }
  hr

app/views/questions/_follow_question.html.slim
#answers-title
  hr
  h3
    | Answers
    - if can? :follow, @question
      =link_to "Follow", follow_question_path(@question), data: {remote: true, method: "POST"}, class: "btn btn-default btn-lg follow-link #{@question.followed_by?(current_user) ? 'hide' : ''}", id: 'follow-question-link'
    - if can? :unfollow, @question
      =link_to "Unfollow", unfollow_question_path(@question), data: { remote: true, method: "DELETE"}, class: "btn btn-default btn-lg follow-link active #{@question.followed_by?(current_user) ? '' : 'hide'}", id: 'unfollow-question-link'

app/views/questions/_question.html.slim
#question-itself style="#{@question.errors.present? ? 'display: none;' : ''}"
  = render 'questions/question_itself'

- if can? :edit, @question
  #question-form style="#{@question.errors.present? ? '' : 'display: none;'}"
    = render partial: 'questions/question_form', locals: { title: "Edit Question" }

app/views/questions/_question_form.html.slim
= bootstrap_nested_form_for @question, label_errors: true, remote: !@question.new_record? do |f|
  = f.alert_message "There " + "is".pluralize(@question.errors.count) + " " + @question.errors.count.humanize + " " + "error".pluralize(@question.errors.count), error_summary: false

  = f.submit "Save Question", class: "btn btn-success"
  = link_to "Cancel", @question.new_record? ? questions_path : @question, remote: !@question.new_record?, data: { confirm: true }, class: "btn btn-danger"

  h1 = title
  = f.text_field :title, help: "If you have short question put it into Title"
  = f.text_field :tags_list, label: "Tags", help: "Type tags separated by comma"
  = f.text_area :question, class: "wysihtml5", size: "100x15"

  = render partial: 'attachments/attachment_form', locals: { form: f, attachment_form_id: "attachment-form" }

  br
  br
  = f.submit "Save Question", class: "btn btn-success"
  = link_to "Cancel", @question.new_record? ? questions_path : @question, remote: !@question.new_record?, data: {confirm: true }, class: "btn btn-danger"

app/views/questions/_question_itself.html.slim
- unless @answer.id
  - if can? :edit, @question
    = link_to "Edit Question", '', class: "btn btn-primary", id: 'edit-question-button'
  - if can? :destroy, @question
    = link_to "Delete Question", @question, data: { method: "DELETE", confirm: true  }, class: "btn btn-danger"
- cache [can?(:see, :author), can?(:rating, @question), @question] do
  = link_to "Back to Questions List", questions_path, class: "btn btn-info"

  h3 =@question.title
  = render partial: 'questions/tags', locals:  { question: @question }
  = render partial: 'ratings/rating_form', locals: { ratingable: @question, rating_path: rating_question_path }
  p.meta-info
    - if can? :see, :author
      | Author:&nbsp;
      strong = @question.user.username
      br
    | Created:&nbsp;
    = @question.created_at.to_s(:long)
    br
    | Last update:&nbsp;
    span.updated_at = @question.updated_at.to_s(:long)


  p =raw @question.question
  = render partial: 'attachments/attachments', object: @question.attachments

  .row
    #question-remarks.col-xs-offset-1.col-xs-10.remarks
      = render partial: 'remarks/remarks', locals: { remarks: @question.remarks, add_action: question_remarks_path(@question) }

app/views/questions/_tags.html.slim
.tags
  - question.tags.each do |tag|
      span class="label #{tag_color(tag.color_index)}" =tag.name

app/views/questions/index.html.slim
- cache collection_cache_key_for :question, can?(:see, :author) do
  .row
    .col-xs-12
      = link_to "Ask New Question", new_question_path, class: "btn btn-primary"
      = link_to "Search", search_path, class: "btn btn-info"
      h1 Questions
      #questions
        - @questions.each do |question|
          div id="question-#{question.id}"
            hr
              p.meta-info
                - if can? :see, :author
                  | Author:&nbsp;
                  strong = question.user.username
                  br
                | Created:&nbsp;
                = question.created_at.to_s(:long)
                br
                | Last update:&nbsp;
                span.updated_at = question.updated_at.to_s(:long)
              = render partial: 'questions/tags', locals: {question: question}
              = render partial: 'ratings/rating_form', locals: {ratingable: question, rating_path: rating_question_path(question)}
              .title
                h4
                  =link_to question.title, question
                  span.badge.answers-count = question.answers.count > 0 ? question.answers.count : nil
                  span class="label label-success has-best-answer#{question.best_answer.nil? ? ' hide' : ''}" Has Best Answer
              .content
                = truncate_html(question.question)

hr
- unless Rails.env.test?
  - if user_signed_in?
    = subscribe_to "/signed_in/questions"
  - else
    = subscribe_to "/questions"

app/views/questions/new.html.slim
.row
  .col-xs-12
    = render partial: 'questions/question_form', locals: { title: "Ask new Question" }

app/views/questions/show.html.slim
.row
  .col-xs-12#question data-question-id="#{@question.id}"
    = render 'questions/question'

.row
  .col-xs-12
    = render 'questions/follow_question'
    = render 'answers/answers'

- if can? :create, Answer
  .row
    .col-xs-12#new-answer
      = render partial: 'answers/answer_form'

- unless Rails.env.test?
  - if user_signed_in?
    = subscribe_to "/signed_in/questions/#{@question.id}"
  - else
    = subscribe_to "/questions/#{@question.id}"

javascript:
  function getUserId() {
    return #{current_user ? current_user.id : 'null'};
  }
  function getQuestionUserId() {
    return #{current_user ? @question.user.id : 'null'};
  }

app/views/questions/show.js.erb
(function() {
    $('#question').html('<%= j render 'questions/question' %>').find('.rating').rating();
    var answers = $('#answers').html('<%= j render 'answers/answers' %>');
    $('#flash').html('<%= j render 'layouts/flash' %>');
    initWidgets();
    <% unless @question.errors.present? %>
    answers.show();
    $('#new-answer').show();
    <% end %>
}).call(this);