config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  root 'questions#index'

  concern :remarkable do
    resources :remarks, only: [:create, :update, :destroy], shallow: true
  end

  resources :questions, except: [:edit], concerns: :remarkable do
    patch :rating, on: :member
    post :follow, on: :member
    delete :unfollow, on: :member
    resources :answers, only: [:create, :update, :destroy], concerns: :remarkable, shallow: true do
      patch :set_as_best, on: :member
      patch :rating, on: :member
    end
  end

  get 'search' => 'search#index', as: :search

  resources :user_confirmation_requests, only: [:new, :edit, :create, :update] do
    get :confirm, on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Ratingable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :remarks, as: :remarkable, dependent: :destroy
  has_many :attachments, as: :attachmentable, dependent: :destroy
  has_many :ratings, as: :ratingable, dependent: :destroy

  validates :question, :user, presence: true
  validates :answer, presence: true, length: { maximum: 2000 }

  after_destroy :no_more_best!
  after_create :send_notification_email

  scope :ordered_by_creation_date, -> { order(created_at: :desc) }

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: proc { |attr| attr['file'].nil? }

  def best!
    question.best_answer = self
  end

  def best?
    question.best_answer == self
  end

  private

  def no_more_best!
    if question.best_answer == self
      question.best_answer = nil
      question.save
    end
  end

  def send_notification_email
    NewAnswerNotificationWorker.perform_async(id)
  rescue
    # Как лучше залоггировать ошибку?
    return
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: :create
  before_action :load_answer, except: :create
  before_action :assign_question, except: :create
  authorize_resource
  after_action :publish, except: :set_as_best, if: "@answer.errors.empty?"
  after_action :publish_answers_info, only: [:set_as_best, :create, :destroy], if: "@answer.errors.empty?"

  respond_to :json

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_user))) do |format|
      format.json { render json: answer_as_json(true) } if @answer.errors.empty?
    end
  end

  def update
    @answer.update(answer_params)
    respond_with @answer do |format|
      format.json { render json: answer_as_json(true) } if @answer.errors.empty?
    end
  end

  def destroy
    respond_with(@answer.destroy) do |format|
      format.json { render json: { id: @answer.id } }
    end
  end

  def set_as_best
    @answer.best!
    if @question.save
      render json: { id: @answer.id }
    else
      render_errors @question
    end
  end

  def rating
    @answer.rating!(current_user, params[:answer][:rating])
    render json: { rating: @answer.rating }
  end

  private

  def answer_params
    params.require(:answer).permit(:answer, attachments_attributes: [:id, :file, :file_cache, :_destroy])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.includes(:attachments).find(params[:id])
  end

  def assign_question
    @question = @answer.question
  end

  def render_errors(source)
    render json: { errors: source.errors.full_messages }, status: :unprocessable_entity
  end

  def answer_as_json(show_author)
    hash = @answer.as_json(include: :attachments)
    if show_author
      hash["author"] = @answer.user.username
    else
      hash.except!("user_id")
    end
    hash["created_at"] = @answer.created_at.to_s(:long)
    hash["updated_at"] = @answer.updated_at.to_s(:long)
    hash["rating"] = @answer.rating
    hash
  end

  def publish
    PrivatePub.publish_to "/questions/#{@question.id}", action: action_name, answer: answer_as_json(false)
    PrivatePub.publish_to "/signed_in/questions/#{@question.id}", action: action_name, answer: answer_as_json(true)
  rescue
    return
  end

  def publish_answers_info
    answers_count = @answer.question.answers.count > 0 ? @answer.question.answers.count : nil
    PrivatePub.publish_to "/questions", action: 'answers_info', question: { id: @answer.question.id, no_best_answer: !@answer.question.best_answer, answers_count: answers_count }
    PrivatePub.publish_to "/signed_in/questions", action: 'answers_info', question: { id: @answer.question.id, no_best_answer: !@answer.question.best_answer, answers_count: answers_count }
  rescue
    # Как лучше залоггировать ошибку?
    return
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: [:index, :create]

  def index
    @answers = @question.answers.all
    respond_with @answers, each_serializer: AnswersSerializer
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer
  end

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_resource_owner)))
  end

  private

  def answer_params
    params.require(:answer).permit(:answer)
  end

  def load_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer-itself style="#{answer.errors.present? ? 'display: none;' : ''}"
  = render partial: 'answers/answer_itself', locals: { answer: answer }

.answer-form style="#{answer.errors.present? ? '' : 'display: none;'}"
  = render partial: 'answers/answer_form', locals: { answer: answer }

hr

app/views/answers/_answer_form.html.slim
= bootstrap_nested_form_for [@question, @answer], label_errors: true, remote: true, data: { type: :json }, html: { id: "answer-form" } do |f|
  #answer-error.alert.alert-danger.well-sm.hide

  = f.submit "Save Answer", class: "btn btn-success answer-submit-button"
  = link_to "Cancel", '', data: {confirm: true, click: 'cancelAnswer' }, class: "btn btn-danger answer-cancel-button"
  br
  br
  = f.text_area :answer, size: "100x15", class: "wysihtml5"

  = render partial: 'attachments/attachment_form', locals: { form: f, attachment_form_id: "answer-attachment-form-new" }

  br
  br
  = f.submit "Save Answer", class: "btn btn-success answer-submit-button"
  = link_to "Cancel", '', data: {confirm: true, click: 'cancelAnswer'}, class: "btn btn-danger answer-cancel-button"
  hr

app/views/answers/_answer_itself.html.slim
- if answer.user == current_user
  .answer-buttons
    = link_to "Edit Answer", '', class: "btn btn-primary edit-answer-button", data: { answer_id: answer.id }
    = link_to "Delete Answer", answer, data: { method: "DELETE", confirm: true, remote: true }, class: "btn btn-danger"
  br

p
  span.label.label-success style="#{answer.best? ? '' : 'display: none;'}" Best
  - if @answer.id.nil? && @author_signed_in
    = link_to "Best", set_as_best_answer_path(answer), data: {method: "PATCH", remote: true}, class: "btn btn-default best-answer-button", style: "#{answer.best? ? 'display: none;' : ''}"
  | &nbsp;&nbsp;
  = answer.answer
= render partial: 'attachments/attachments', object: answer.attachments

.row
  .answer-remarks.col-xs-offset-1.col-xs-10.remarks
    = render partial: 'remarks/remark', locals: { remarks: answer.remarks, add_action: answer_remarks_path(answer) }

app/views/answers/_answers.html.slim
#answers
  - @answers.each do |answer|
    .answer id="answer-#{answer.id}"
      - if can?(:edit, answer) || can?(:destroy, answer)
        .answer-buttons
          - if can? :edit, answer
            = link_to "Edit Answer", '', data: { action: "#{answer_path(answer)}" }, class: "btn btn-primary edit-answer-button"
          - if can? :destroy, answer
            = link_to "Delete Answer", answer, data: { type: :json, method: "DELETE", confirm: true, remote: true, success: 'answerDeleteSuccess', error: 'answerDeleteError' }, class: "btn btn-danger delete-answer-button"
        br

      - cache [can?(:see, :author), can?(:rating, answer), answer] do
        p.meta-info
          - if can? :see, :author
            | Author:&nbsp;
            strong = answer.user.username
            br
          | Created:&nbsp;
          = answer.created_at.to_s(:long)
          br
          | Last update:&nbsp;
          span.updated_at = answer.updated_at.to_s(:long)
        = render partial: 'ratings/rating_form', locals: {ratingable: answer, rating_path: rating_answer_path(answer)}
        p
          span.label.label-success.best-answer style="#{answer.best? ? '' : 'display: none;'}" Best
          - if can? :set_as_best, answer
            = link_to "Best", set_as_best_answer_path(answer), data: {method: "PATCH", remote: true}, class: "btn btn-default best-answer-button", style: "#{answer.best? ? 'display: none;' : ''}"
        p.answer-content
          = raw answer.answer
        = render partial: 'attachments/attachments', object: answer.attachments

        .row
          .answer-remarks.col-xs-offset-1.col-xs-10.remarks
            = render partial: 'remarks/remarks', locals: { remarks: answer.remarks, add_action: answer_remarks_path(answer) }

        hr

app/views/answers/_new_answer.html.slim
- if user_signed_in? && @answer.new_record?
  = render partial: 'answers/answer_form', locals: { answer: @answer }