config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  root 'questions#index'

  concern :remarkable do
    resources :remarks, only: [:create, :update, :destroy], shallow: true
  end

  resources :questions, except: [:edit], concerns: :remarkable do
    patch :rating, on: :member
    post :follow, on: :member
    delete :unfollow, on: :member
    resources :answers, only: [:create, :update, :destroy], concerns: :remarkable, shallow: true do
      patch :set_as_best, on: :member
      patch :rating, on: :member
    end
  end

  get 'search' => 'search#index', as: :search

  resources :user_confirmation_requests, only: [:new, :edit, :create, :update] do
    get :confirm, on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

end

app/models/remark.rb
class Remark < ActiveRecord::Base
  belongs_to :user
  belongs_to :remarkable, polymorphic: true, touch: true

  validates :user, :remarkable, :remark, presence:  true
  validates :remark, length: { maximum: 2000 }

  scope :ordered_by_creation_date, -> { order(created_at: :asc) }
end

app/controllers/remarks_controller.rb
class RemarksController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :load_remarkable, only: :create
  after_action :publish, if: "@remark.errors.empty?" #, unless: "Rails.env.test?"

  respond_to :json

  def create
    respond_with(@remark = @remarkable.remarks.create(remark_params.merge(user: current_user))) do |format|
      format.json { render :show, status: :created } if @remark.errors.empty?
    end
  end

  def update
    @remark.update(remark_params)
    respond_with(@remark) do |format|
      format.json { render :show } if @remark.errors.empty?
    end
  end

  def destroy
    respond_with(@remark.destroy) do |format|
      format.json { render json: { id: @remark.id } }
    end
  end

  private

  def remark_params
    params.require(:remark).permit(:remark)
  end

  def load_remarkable
    if params[:answer_id]
      @remarkable = Answer.find(params[:answer_id])
    else
      @remarkable = Question.find(params[:question_id])
    end
  end

  def publish
    remark = @remark.as_json(except: :user_id)
    remark["created_at"] = @remark.created_at.to_s(:long)
    remark["updated_at"] = @remark.updated_at.to_s(:long)
    question = @remark.remarkable.is_a?(Answer) ? @remark.remarkable.question : @remark.remarkable
    PrivatePub.publish_to "/questions/#{question.id}", action: action_name, remark: remark

    remark["user_id"] = @remark.user.id
    remark["author"] = @remark.user.username
    PrivatePub.publish_to "/signed_in/questions/#{question.id}", action: action_name, remark: remark
  rescue
    # Как лучше залоггировать ошибку?
    return
  end
end

app/helpers/remarks_helper.rb
module RemarksHelper
end

app/views/remarks/_remark.html.slim
- remarks.ordered_by_creation_date.each do |remark|
  .well.well-sm id="remark-#{remark.id}"
    - if can?(:edit, remark) || can?(:destroy, remark)
      - if can? :edit, remark
        = link_to "Edit", '', data: { action: "#{remark_path(remark)}" }, class: "btn btn-default edit-remark"
      - if can? :destroy, remark
        = link_to "Delete", remark, data: { type: :json, method: "DELETE", remote: true, success: 'remarkDeleteSuccess', error: 'remarkDeleteError', confirm: true}, class: "btn btn-default delete-remark"
      br
      br
    p.meta-info
      - if can? :see, :author
        | Author:&nbsp;
        strong = remark.user.username
    .remark-content
      = raw remark.remark
- if can? :create, Remark
  = link_to "Add Remark", '', data: { action: add_action }, class: "btn add-remark"

app/views/remarks/_remark_form.html.slim
- cache 'remark_form' do
  #remark-well.well.well-sm.hide
    = bootstrap_form_tag label_errors: true, remote: true, data: { type: 'json' }, html: { class: 'edit_remark', id: 'remark-form' } do |f|
      #remark-error.alert.alert-danger.well-sm.hide

      = f.text_area :remark, size: "100x15", hide_label: true, name: 'remark[remark]', id: 'remark-textarea'

      = f.submit "Save Remark", class: "btn btn-success", id: 'remark-submit'
      = link_to "Cancel", '', data: { confirm: true, click: 'cancelRemark' }, class: "btn btn-danger", id: 'remark-cancel'

app/views/remarks/_remarks.html.slim
- remarks.ordered_by_creation_date.each do |remark|
  .well.well-sm id="remark-#{remark.id}"
    - if can?(:edit, remark) || can?(:destroy, remark)
      - if can? :edit, remark
        = link_to "Edit", '', data: { action: "#{remark_path(remark)}" }, class: "btn btn-default edit-remark"
      - if can? :destroy, remark
        = link_to "Delete", remark, data: { type: :json, method: "DELETE", remote: true, success: 'remarkDeleteSuccess', error: 'remarkDeleteError', confirm: true}, class: "btn btn-default delete-remark"
      br
      br
    - cache [can?(:see, :author), remark] do
      p.meta-info
        - if can? :see, :author
          | Author:&nbsp;
          strong = remark.user.username
          br
        | Created:&nbsp;
        = remark.created_at.to_s(:long)
        br
        | Last update:&nbsp;
        span.updated_at = remark.updated_at.to_s(:long)
      .remark-content
        = raw remark.remark
- if can? :create, Remark
  = link_to "Add Remark", '', data: { action: add_action }, class: "btn add-remark"